backend:
  name: git-gateway
  branch: master  # zmień na 'master' jeśli masz inną gałąź

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - name: "homepage"
        file: "index.html"
        label: "Strona główna"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Opis", name: "description", widget: "text" }
