backend:
  name: git-gateway
  branch: main

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - file: "index.html"
        label: "Strona główna"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Opis", name: "description", widget: "text" }
